### ISSUE TITLE
Adb executable not found error

### ISSUE THREAD

**Issue by Nagarjunaavula** [nwlunatic/appium-autoregister#19]
When i try to run autoregister.py i am getting "Adb executable not found error" but i have the adb.exe at the specified location. I have also added ANDROID_HOME in system variables.
![1](https://cloud.githubusercontent.com/assets/655820/26444725/23a1ecc8-415b-11e7-9e48-82e17199b22d.png)
![2](https://cloud.githubusercontent.com/assets/655820/26444727/23a7788c-415b-11e7-86bf-1fdf306041cb.png)
![3](https://cloud.githubusercontent.com/assets/655820/26444726/23a2c71a-415b-11e7-9dd9-52ced23dbbbf.png)

**Comment by nwlunatic** [comment]
Hello!

That is probably because I haven't been targeting windows while writing autoregister, and it's looking for `adb` executable file, not `adb.exe`.
But you can probably set APPIUM_EXECUTABLE=<path_to_appium_executable> directly.

try this:
```
set APPIUM_EXECUTABLE=path\to\your\adb.exe
python appium-autoregister.py
```

Also notice you should use `python3` as it's written in readme

**Comment by Nagarjunaavula** [comment]
Hi nwlunatic,

Thanks for the response. I am sorry to ask you again.

can you please explain this 

> But you can probably set APPIUM_EXECUTABLE=<path_to_appium_executable> directly.

I have set APPIUM_EXECUTABLE environment variable in my system.
APPIUM_EXECUTABLE C:\Program Files (x86)\Appium {not added \Appium.exe}

> try this:
> set APPIUM_EXECUTABLE=path\to\your\adb.exe 

{Why appium executable = to adb path here ? }
python appium-autoregister.py

> Also notice you should use python3 as it's written in readme 

i have updated my python to 3.6+ now.

so can you please guide me with the step by step process to execute this on windows environment. 

Note: I have installed appium on my system and gave the set APPIUM_EXECUTABLE in environment variables with the appium installation directory.

**Comment by nwlunatic** [comment]
No, you're right, my mistake.
I'll try to fix this soon.

Just as a quick fix you can try replacing
https://github.com/nwlunatic/appium-autoregister/blob/master/android/adb.py#L19
to
```python
adb = os.path.join(android_home, 'platform-tools', 'adb.exe')
```

**Comment by Nagarjunaavula** [comment]
In the latest version i am getting the below error. can you please help me on this.

![adb](https://cloud.githubusercontent.com/assets/655820/26541840/0e6ce02a-4475-11e7-89dc-ee96988fb4b9.png)

**Comment by nwlunatic** [comment]
Can you, please, verify that command
```
C:\Program files (x86)\Appium --port 51945 ...
```
is not working because of permissions?
It seems like you are running under user ADMIN and it not have permissions to run appium for example

**Comment by nwlunatic** [comment]
As I can see adb.exe is working just fine. So I think it's better to move current problem to another issue, if you dont mind

**Comment by Nagarjunaavula** [comment]
Sure nwlunatic, i have moved this issue as new one. Please have a look at 
#21
